### ISSUE TITLE
Questions on generating flow

### ISSUE THREAD

**Issue by golddohyun** [ltkong218/IFRNet#26]
Thank you for your source code! I want to train your model by using Vimeo90k data. I tried to run the generate_flow.py but I've got these errors.
On your code on run.py of liteflownet, I've realized that the 297th line on the run.py might have a problem.
I accessed the link ("http://content.sniklaus.com/github/pytorch-liteflownet") where the error occurred directly, but the page of the link seems to have disappeared. When I tried the actual connection, only the phrase "no so much file or directory" came out.

and below is the error printed on my log.txt file!

Downloading: "http://content.sniklaus.com/github/pytorch-liteflownet/network-default.pytorch" to /home/chaeyun/.cache/torch/hub/checkpoints/network-default.pytorch
Traceback (most recent call last):
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_flow.py", line 59, in <module>
    flow_t0 = pred_flow(imgt, img0)
  File "generate_flow.py", line 36, in pred_flow
    flow = estimate(img1, img2)
  File "/data/projects/chaeyun/IFRNet/liteflownet/run.py", line 341, in estimate
    netNetwork = Network().cuda().eval()
  File "/data/projects/chaeyun/IFRNet/liteflownet/run.py", line 297, in __init__
    self.load_state_dict({ strKey.replace('module', 'net'): tenWeight for strKey, tenWeight in torch.hub.load_state_dict_from_url(url='http://content.sniklaus.com/github/pytorch-liteflownet/network-' + arguments_strModel + '.pytorch').items() })
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/site-packages/torch/hub.py", line 727, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/site-packages/torch/hub.py", line 593, in download_url_to_file
    u = urlopen(req)
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/urllib/request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/chaeyun/miniconda3/envs/cytorch/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
srun: error: node01: task 0: Exited with exit code 1

**Comment by ltkong218** [comment]
To solve your problems, I suggest that:
1. Comment out this line of [code](https://github.com/ltkong218/IFRNet/blob/b646b54d85d4d224bcddad003663fdd984575cef/liteflownet/run.py#L297) and umcomment this line of [code](https://github.com/ltkong218/IFRNet/blob/b646b54d85d4d224bcddad003663fdd984575cef/liteflownet/run.py#L298) in <code>./liteflownet/run.py</code>.
2. Download the pre-trained LiteFlowNet parameters in this [link](https://www.dropbox.com/sh/hrewbpedd2cgdp3/AADbEivu0-CKDQcHtKdMNJPJa?dl=0), and then put the file <code>network-default.pth</code> into the dir of <code>./liteflownet/network-default.pth</code>.

**Comment by golddohyun** [comment]
It worked! thank you so much :)
